---
# RolloutsでBlue/Green deploymentを実装できるように以下２行編集
apiVersion: argoproj.io/v1alpha1 
kind: Rollout 
# apiVersion: apps/v1
# kind: Deployment
metadata:
  name: portal-nginx
spec:
  selector:
    matchLabels:
      run: portal-nginx
  template:
    metadata:
      labels:
        run: portal-nginx
    spec:
      containers:
        - name: apache
          image: apache
# RolloutsでBlue/Green deploymentを実装できるように追記
  strategy:
    blueGreen: 
      # 本番アクセス用のServiceの名前
      activeService: rollout-bluegreen-active
      # Previewアクセス用のServiceの名前
      previewService: rollout-bluegreen-preview
      # 手動昇格の有無
      autoPromotionEnabled: true
      # オプション Preview環境限定でreplicasの上書き
      previewReplicaCount: 1
      # オプション ReplicaSetが準備完了になってから自動昇格するまでの時間
      autoPromotionSeconds: 300
      # オプション 新Verにルーティングを切り替えた後に旧VerのPodのスケールダウンを開始させるまでの時間
      scaleDownDelaySeconds: 30