---
#apiVersion: v1
#kind: Service
#metadata:
#  name: portal-nginx
#  labels:
#    run: portal-nginx
#spec:
#  ports:
#    - port: 80
#  selector:
#    run: portal-nginx
kind: Service
apiVersion: v1
metadata:
  name: rollout-bluegreen-active
  labels:
    app: portal-nginx
spec:
  selector:
    app: portal-nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: rollout-bluegreen-preview
  labels:
    app: portal-nginx
spec:
  selector:
    app: portal-nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
